### ISSUE TITLE
Error: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Gasman2014** [resetnow/partkeepr-label-gen#1]
I have a functioning zint installation. I have cloned your repo and npm installed it as per instructions.
I have fed a simple .csv file in (part1, location1 etc). Your script generates the requested output directory with an index.html file and an 'images' directory but fails with the following error

Error: Cannot read property 'replace' of undefined

The index.html file is correctly formed and the 'images' directory is correctly created but it contains no files.

**Comment by vlad-ivanov-name** [comment]
Thanks for reporting it. I have added a backtrace to the error message, could you please try again and post it?

**Comment by vlad-ivanov-name** [comment]
Having your csv would also be useful (not the whole thing, 5-10 lines).

**Comment by Gasman2014** [comment]
Thanks for quick response. I have run again with backtrace;

Error: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at escape (/Users/johnpateman/Kicad/partkeepr-label-gen/index.js:139:6)
    at saveHTML (/Users/johnpateman/Kicad/partkeepr-label-gen/index.js:147:6)
    at main (/Users/johnpateman/Kicad/partkeepr-label-gen/index.js:163:4)
    at /Users/johnpateman/Kicad/partkeepr-label-gen/index.js:170:2
    at Object.<anonymous> (/Users/johnpateman/Kicad/partkeepr-label-gen/index.js:171:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

FYI I am running this on a Mac - OS X 10.11.
I can't attach my .csv file (not permitted) but it is as follows (and was typed in Atom so shouldn't have any funny line endings or anything)

Test1, Rack0
Test2, Rack1
Test3, Rack2
Test4, Rack3
Test5, Rack4
Test6, Rack5
Test7, Rack6
Test8, Rack7

**Comment by vlad-ivanov-name** [comment]
The csv file is probably missing one line which should be generated by partkeepr. In particular, the script looks for columns titled `name` and `storageLocation.name` (see <a href="https://github.com/resetnow/partkeepr-label-gen/blob/master/index.js#L117">here</a>). The error message could be more informative — that's on me. Anyway, your file should look like this:

```
name,storageLocation.name
Test1, Rack0
Test2, Rack1
Test3, Rack2
Test4, Rack3
Test5, Rack4
Test6, Rack5
Test7, Rack6
Test8, Rack7
```

**Comment by Gasman2014** [comment]
Thank you - will try that.

 I had some minor issues exporting from PartKeepr - the export function generated a 'blob' and not a clean .csv with a lot of extraneous lines so I just stripped them all out leaving the bare text. 

John Pateman

**Comment by Gasman2014** [comment]
Thank you - adding back in the `name, storageLocation.name` solved the problem.
I had some slight problems exporting from PartKeepr - it returns a 'blob' file with a lot of extraneous formatting rather than a bare .csv. I stripped quite a lot out this out but obviously to much! Copying and pasting works fine.

This looks a really useful utility - thank you for releasing it and thank you for your helpful support.

**Comment by vlad-ivanov-name** [comment]
Glad I could help. Regarding the partkeepr export — it used to work fine.
Note that having quotes and backslashes in csv is fine and should be
handled as well. So are additional columns — they will be skipped.

14 нояб. 2016 г. 13:44 пользователь "John" notifications@github.com
написал:
