### ISSUE TITLE
Incorrect encoding for non-alphanumeric data

### ISSUE THREAD

**Issue by Gasman2014** [resetnow/partkeepr-label-gen#2]
My parts locations begin '$nn-nn' where n is a digit 0-9. e.g. `$04-02`.
However, this location is encoded by partkeepr-label-gen as `'/bin/sh4-02'`

Running `zint -d "$01-01"` results in a barcode reading` '/bash/sh1-01'`
However running `zint -d '$01-01'` produces the correct format barcode.

Not sure if this is a 'feature' of zint - both single and double quotes are  used in the documentation.

**Comment by vlad-ivanov-name** [comment]
It's bash expanding `$0`. I have updated the code to use single quotes. Thanks for reporting it.

**Comment by vlad-ivanov-name** [comment]
Feel free to reopen if you have any problems.
